"""Add is_public to SpriteModel

Revision ID: 39661cb9d589
Revises: 733d6fb2efe9
Create Date: 2026-02-21 13:29:03.307958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39661cb9d589'
down_revision: Union[str, Sequence[str], None] = '733d6fb2efe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprites', sa.Column('is_public', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprites', 'is_public')
    # ### end Alembic commands ###
