"""Add play_count to SpriteModel

Revision ID: 48e4ac84df28
Revises: 39661cb9d589
Create Date: 2026-02-21 13:45:36.656041

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48e4ac84df28"
down_revision: Union[str, Sequence[str], None] = "39661cb9d589"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sprites",
        sa.Column("play_count", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sprites", "play_count")
    # ### end Alembic commands ###
